spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/bin/testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 1111
  jpa:
    show-sql: true
    database: h2
    #    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true