jwt:
  header: Authorization
  secret: Tm92YUhvbWVQYWdlc2FkZmFzZGZhc2RmYXNkZnNhZGY=
  access-token-validity-in-seconds: 6000 # 10 min

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
logging.level:
  org.hibernate.SQL: debug

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: secret
    property:
      prefix: ENC(
      suffix: )